# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30e643c57b78e7edee0211494ed2f0c035ef5f90b408a1aa2ef9efeddfe3e974dfff6839d8c5432dceea33a5933e741798d33254b8f5fc351cf0005b4ee9566a

test:
  secret_key_base: 8b23e1cfa5bbc32df70ff5191dca02c317ba8398537fecfb693a6b2b2bcca251354486456483137f74cbda298e87bd143d77939a054e710795bbad358c1ab5c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
